#!/bin/bash
cd /home/murpheus/Nextjs/locale-rent

cat > .env.local << 'EOF'
NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=YOUR_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=YOUR_SERVICE_ROLE
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=YOUR_STRIPE_PK
STRIPE_SECRET_KEY=YOUR_S...
